jenkinsci/build-pipeline-plugin

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/PipelineBuild.java, src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/bpp.jelly, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/PipelineBuildTest.java
If a job has two upstream dependencies and it has been triggered by anything except the manual trigger it will always take the first upstream job as the upstream dependency even if it is incorrect. Added check to not add a null Cause if upstream build is null.
=> JENKINS-20499 

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/bpp.jelly, src/main/webapp/js/build-pipeline.js
Restarting the failed job manually will reflect in changes in the pipeline and allow you to proceed with the next build in the pipeline.
Just made changes to use 'triggerBuild' function instead of 'rebuild' and 'rerun'. 'triggerBuild' provides information about the upstream build, where two others don't. Restarting or rerunning was causing a build not to be considered as a part of the pipeline (where it should actually be).
=> [Fixed JENKINS-22210]: restarting the failed job manually

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/bpp.jelly, src/main/webapp/js/build-pipeline.js
Reverts jenkinsci/build-pipeline-plugin#66
Caused regression with not working "re-run" buttons.
=> Revert "[Fixed JENKINS-22210]: restarting the failed job manually"

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTriggerTest.java, src/test/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest/testMyUserIdCauseConversion/config.xml, src/test/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest/testMyUserIdCauseConversion/jobs/B/builds/2015-01-06_09-41-20/build.xml, src/test/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest/testMyUserIdCauseConversion/jobs/B/config.xml
Remove the serialization of the User object within MyUserIdCause. Kept MyUserIdCause for backwards compatibility but is now just a simple subclass of the core class UserIdCause. 
This also fixes the JENKINS-19755 "Manual step "started by" username changes to anonymous after restart" since it now can load the correct user who triggered the build.
After upgrading it is possible to "Manage Old Data" to remove User object serialization of MyUserIdCause.
=> [FIXED JENKINS-22665] Fixes for JENKINS-22665 and JENKINS-19755

.gitignore, pom.xml, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/main/webapp/js/build-pipeline.js, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTriggerTest.java
This PR fixes JENKINS-30801, a bug in the 're-run' feature where `Action` objects from a previous run were copied over to the re-run.
This is desirable for certain actions: `CauseAction` and `ParametersAction` are necessary to preserve upstream/downstream relationship and upstream trigger context.
However, `Action` is also used by `Builder` and `Publisher` to persist and summarize stuff about what they built (for example, test result information). This is meaningful for only that current `Run`, and should not be relevant at all for a re-run.
The fix here is to filter out actions and only include `CauseAction` and `ParametersAction`. `CauseAction` with a `UserId` cause is also excluded because the re-run will explicitly include a new `MyUserIdAction` for the user doing the re-triggering. …
=> Fix for JENKINS-30801

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java
The cause list is immutable as described in the comments of
[JENKINS-33467](https://issues.jenkins-ci.org/browse/JENKINS-33467).
=> Fix JENKINS-33591: Manual steps broken in Jenkins ver. 1.653

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildForm.java
[JENKINS-34370](https://issues.jenkins-ci.org/browse/JENKINS-34370)
Context: line 102 of `BuildForm.java`.
The method `getParameterDefinitionNames()` from the class `ParametersDefinitionProperty.java` can return `null` and this is not being controlled before getting into the iteration of their expected `AbstractList<String>`.
@reviewbybees
=> [JENKINS-34370] NPE coming from BuildForm.java in line 102

src/main/java/au/com/centrumsystems/hudson/plugin/util/BuildUtil.java, src/test/java/au/com/centrumsystems/hudson/plugin/util/BuildUtilTest.java
[JENKINS-34722](https://issues.jenkins-ci.org/browse/JENKINS-34722)
Currently the `BuildUtil.getDownstreamBuild` will iterate through all of the downstream project builds even if the upstream build never executed the downstream job. This PR adds a system property which can limit the number of downstream builds to search. A unit test has also been added to confirm that the limit is properly being reached and does not exceed the max number of builds to search for when looking for downstream builds.
@reviewbybees
=> [FIXED JENKINS-34722] Performance improvement to not load all jobs

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java
Jenkins core made CauseAction.getCauses an unmodifiable collection
([JENKINS-33467](https://issues.jenkins-ci.org/browse/JENKINS-33467)) - so we need to make a copy.
=> Fixed JENKINS-33935

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java
I've encountered a bug with Jenkins where git revision params are not passed through to a rebuild done via a build pipeline. This happens due to `RevisionParameterAction` being filtered out in job rerun logic.
To avoid a dependency on the git plugin, this is doing a comparison against the class name. If you've got a better way to do this then I'm all ears!
I've confirmed locally that this fixes the issue and passes revision params correctly to a rerun.
=> Keep revision params on rerun of a build

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/extension/BuildCardExtension.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTriggerTest.java
[Fixed JENKINS-23532] Manually triggering build will now search other folders for the upstream project
=> [Fixed JENKINS-23532] Search Folders when trying to find upstream project

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/extension/BuildCardExtension.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTriggerTest.java
Refactor retrieveUpstreamProjectTriggerConfig to be more consistent and therefore readable.
Allow all types of triggers to receive relative path names to their downstream projects.
=> Refactor retrieving the upstream project's trigger config to allow for finding relative path names

src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/extension/PipelineHeaderExtension/columnHeader.jelly, src/main/webapp/css/main.css
I've noticed that when multiple variables are listed on the Pipeline view it can push out pipelines below and eventually the layout is affected. I've included a screen capture representative of this.
I've tested this on various machines with various browsers and different monitor resolutions.
This pull request suggests some minor changes to the CSS to accommodate for the over-spill from the variable list. As shown in this screen capture.
I have carried out the testing with Chrome, IE/Edge & Firefox on several machines and it has maintained the layout.
Thank you for considering this amendment.
=> Amending CSS and Div Structure to accommodate variables listed

pom.xml, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/test/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineViewTest.java
@reviewbybees 
Empty views should be visible to users who have `View/Configure` permissions: https://issues.jenkins-ci.org/browse/JENKINS-51573
=> [JENKINS-51573] Fix the visibility of Empty views.

pom.xml, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView.java, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/Grid.java, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/extension/AbstractNameValueHeader.java, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTrigger.java
Earlier changes in the plugin ( d8d4635b4001feadd575e731c29a23e8e4593851 ) mistakenly included the Jenkins test harness as a compile time dependency.  That caused many jar files to be bundled into the plugin binary as transitive dependencies.  Prevent those transitive dependencies by relying on the Jenkins test harness dependency that is provided by the parent pom.
- [JENKINS-72353](https://issues.jenkins.io/browse/JENKINS-72353) Rely on jenkins test harnesss from parent
Includes two other relatively minor changes that resolve compilation warnings with Java 11.
- 16e3569ece51e17d862dbfee6e9a2afc59ada080 Include matrix-auth dependency only once
- f320bbf379f21617159dd90d3da7602a53869bb6 Fix Javadoc warnings from Java 11
Plugin size by version (noting that 2.0.1-xx is not released)
| …
=> [JENKINS-72353] Do not include test harness in plugin binary

src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/bpp.jelly
[JENKINS-72581](https://issues.jenkins.io/browse/JENKINS-72581) describes the failure with Jenkins 2.426.2.  The "Run" button reports a JavaScript error rather than starting the build.  With this change, the build starts as expected.  Change was made based on the instructions in the [Prototype.js removal blog post](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/).
Does not fix the "Delete" button.  That needs to be replaced with the modern version of delete that will use a modal dialog.
Interactive testing confirmed that I can duplicate the problem before this change and that after this change, the Run button behaves as expected.
```[tasklist]
```
=> [JENKINS-72581] Replace Prototype.js in the 'Run' button

pom.xml, src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/bpp.jelly
We are about to deprecate the jQuery 1.x Jenkins library plugin, since it is not CSP compliant. In preparation for this deprecation, migrate from jQuery 1.x to 3.x.
To test this, I created an empty Build Pipeline view and verified in the browser's debugger that the `jQuery` object referred to jQuery 3.x.
@dalvizu Can this please be merged and released?
=> Migrate from jQuery 1.x to 3.x

src/main/webapp/js/jquery.fancybox-1.3.4.js
Manually tested.
This recent upgrade to jQuery 3.x in #140 breaks the existing functionality in https://github.com/jenkinsci/build-pipeline-plugin/blob/master/src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/extension/BuildCardExtension/buildCardTemplate.jelly#L64
```
[Error] TypeError: content.get(0).style.removeAttr is not a function. (In 'content.get(0).style.removeAttr('filter')', 'content.get(0).style.removeAttr' is undefined)
_finish (jquery.fancybox-1.3.4.js:580)
(anonymous function) (jquery.min.js:2:61095)
c (jquery.min.js:2:25310)
fireWith (jquery.min.js:2:26055)
u (jquery.min.js:2:57809)
(anonymous function) (jquery.min.js:2:62806)
dt (jquery.min.js:2:57126)
```
After change, works as expected.
=> fix: Update jQuery filter removal syntax for 3.x compatibility

src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/main_dashboard.jelly, src/main/resources/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildPipelineView/toggle-build-details.js
[JENKINS-74055](https://issues.jenkins.io/browse/JENKINS-74055)
The current functionality is broken:
1. The code isn’t triggered in the pipeline view, likely intentional, as the file isn’t included in the sources. The code is supposed to toggle build details/actions for each card when clicking the header (Project Build #), but instead, it redirects users to the build status page.
2. The code isn’t compatible with the jQuery 3 update #140.
I moved the script to `BuildPipelineView/bpp.jelly` to execute it within the pipeline view. After making it compatible with jQuery 3, the toggling behavior now conflicts with the existing redirection to the build status page.
``` 
<script type="text/javascript">
// show/hide build details
jQuery(function() {
jQuery(".header").click(function() {
var …
```
=> [JENKINS-74055] Extract inline script block in `BuildPipelineView/main_dashboard.jelly`

src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/BuildForm.java, src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/ProjectForm.java
IDs were sometimes being returned as negative ints which break pipeline functionality. 
ref:
- #148
=> Mask negative bits to prevent negative projectIds in `BuildForm.java` and `ProjectForm.java`
